version: 2

models:
  - name: stg_listings
    columns:
      - name: id
        tests:
          - not_null
          - unique

      - name: host_id
        tests:
          - not_null
models:
  - name: stg_listing_history
    columns:
      - name: listing_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg_listings')
              field: listing_id
models:
  - name: stg_reviews
    columns:
      - name: id
        tests:
          - not_null
          - unique

      - name: host_id
        tests:
          - not_null
